// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateSubmissionRequest create submission request
//
// swagger:model CreateSubmissionRequest
type CreateSubmissionRequest struct {

	// score worth
	// Required: true
	ScoreWorth *float64 `json:"score_worth"`

	// timestamp
	Timestamp int64 `json:"timestamp,omitempty"`

	// user id
	// Required: true
	// Format: uuid
	UserID *strfmt.UUID `json:"user_id"`
}

// Validate validates this create submission request
func (m *CreateSubmissionRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateScoreWorth(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateSubmissionRequest) validateScoreWorth(formats strfmt.Registry) error {

	if err := validate.Required("score_worth", "body", m.ScoreWorth); err != nil {
		return err
	}

	return nil
}

func (m *CreateSubmissionRequest) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("user_id", "body", m.UserID); err != nil {
		return err
	}

	if err := validate.FormatOf("user_id", "body", "uuid", m.UserID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create submission request based on context it is used
func (m *CreateSubmissionRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateSubmissionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSubmissionRequest) UnmarshalBinary(b []byte) error {
	var res CreateSubmissionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
