// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaginatedResponse paginated response
//
// swagger:model PaginatedResponse
type PaginatedResponse struct {

	// How many result returned in data
	// Example: 50
	Count int64 `json:"count,omitempty"`

	// limit
	// Example: 5
	Limit int64 `json:"limit,omitempty"`

	// offset
	// Example: 10
	Offset int64 `json:"offset,omitempty"`

	// How many total results exists for query
	// Example: 100
	Total int64 `json:"total,omitempty"`
}

// Validate validates this paginated response
func (m *PaginatedResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this paginated response based on context it is used
func (m *PaginatedResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaginatedResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaginatedResponse) UnmarshalBinary(b []byte) error {
	var res PaginatedResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
